/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frames;

import dados.Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import persistencia.ControladorDePersistencia;

/**
 *
 * @author Guilherme
 */
public class CadastrarAuxiliarGeral extends javax.swing.JFrame {

    private int tipo;
    private MenuPrincipal mp;
    
    private int selecionado;
    
    private Funcionario funci;
    private ConsultarFuncionario cf;

    public CadastrarAuxiliarGeral() {
        initComponents();
        this.tipo = 3;
        this.setLocationRelativeTo(null);
    }
    
    public CadastrarAuxiliarGeral(MenuPrincipal m) {
        initComponents();
        this.tipo = 3;
        selecionado = 1;
        mp = m;
        this.setLocationRelativeTo(null);
    }
    
    public CadastrarAuxiliarGeral(ConsultarFuncionario c,Funcionario f1) {
        initComponents();
        this.tipo = 3;
        cf = c;
        selecionado = 2;
        funci = new Funcionario();
        funci.clonarFuncionario(f1);
        jTextField3.setText(funci.getNome());
        jTextField2.setText(funci.getEndereco());
        jTextField4.setText(funci.getTelefone());
        jTextField5.setText(""+funci.getSalario());
        jTextField1.setText(funci.getEmail());
        //jTextField1.setEditable(false);
        jComboBox2.setSelectedIndex(funci.getTipo()-3);
        jButton2.setText("Alterar");
        jLabel1.setText("Alterar Auxiliar Geral");
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Creates new form CadastrarAluno    
    /**
     * Creates new form CadastrarAluno
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastrar Auxiliar Geral");

        jLabel2.setText("Nome:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Salário:");

        jLabel8.setText("Endereço:");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("E-mail:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Cargo:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Faxineiro", "Copeiro", "Vigia" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextField5)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(selecionado == 1){
            mp.setEnabled(true);
        }
        if(selecionado == 2){
            cf.setEnabled(true);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean funcionarioNaoExiste(Funcionario fc){
        try{
            ControladorDePersistencia con = new ControladorDePersistencia();
            ArrayList<Funcionario> lf = con.carregaFuncionario();
            for(Funcionario f1:lf){
                if(f1.getEmail().toUpperCase().equals(fc.getEmail().toUpperCase())){
                    return false;
                }
            }
        }
        catch(Exception ex){
            
        }
        return true;
    }
    
    public boolean emailUsado(Funcionario fc){
        try{
            ControladorDePersistencia con = new ControladorDePersistencia();
            ArrayList<Funcionario> lf = con.carregaFuncionario();
            for(Funcionario f1:lf){
                if(f1.getEmail().toUpperCase().equals(fc.getEmail().toUpperCase())){
                    if(f1.getId() != fc.getId()){
                        return true;
                    }
                }
            }
        }
        catch(Exception ex){
            
        }
        return false;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Funcionario funcionario = null;
        String Nome, Endereco, Telefone, Email, Senha, ConfSenha;
        int Status;
        double Salario;
        
        try{
            
            Nome = this.jTextField3.getText().toString();
            if (Nome.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um nome.","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            Endereco = this.jTextField2.getText().toString();
            if (Endereco.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um endereco.","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            Telefone = this.jTextField4.getText().toString();
            if (Telefone.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um telefone válido.","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            try{
                if (this.jTextField5.getText().toString() == ""){
                    JOptionPane.showMessageDialog(this,"Insira um Salário.","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                else{
                    Salario = Double.parseDouble(this.jTextField5.getText().toString());
                }
            }
            catch(Exception exs){
                JOptionPane.showMessageDialog(this,"Insira um Salário válido.","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
            }
            Email = this.jTextField1.getText().toString();
            if (Email.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um Email válido.","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            int cargo = 0;
            cargo = jComboBox2.getSelectedIndex();
            tipo = tipo + cargo;
            Status = 1;
            
            funcionario = new Funcionario(Nome, Endereco, Telefone, Salario, Email, "", tipo, Status);
            //System.out.println(funcionario.getTipo());
            if(selecionado == 1){
                if(funcionarioNaoExiste(funcionario)){
                    ControladorDePersistencia per = new ControladorDePersistencia();
                    boolean b = per.cadastraFuncionario(funcionario);

                    if(b){
                        JOptionPane.showMessageDialog(this,"Funcionário Cadastrado com Sucesso.","Mensagem",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Erro ao cadastrar Funcionario.","Warning",JOptionPane.WARNING_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Funcionário já existe");
                    return;
                }
            }
            if(selecionado == 2){
                funcionario.setId(funci.getId());
                if(emailUsado(funcionario)){
                    JOptionPane.showMessageDialog(this,"Email utilizado por outro usuario");
                    return;
                }
                ControladorDePersistencia per = new ControladorDePersistencia();
                boolean b = per.alteraFuncionario(funcionario);

                if(b){
                    JOptionPane.showMessageDialog(this,"Funcionário Alterado com Sucesso.","Mensagem",JOptionPane.INFORMATION_MESSAGE);
                    cf.setEnabled(true);
                    cf.reload();
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Erro ao alterar Funcionario.","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
            }
            
            
        }
        catch(Exception ex){
            
        }
        
        if(selecionado == 1){
            mp.setEnabled(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAuxiliarGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAuxiliarGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAuxiliarGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAuxiliarGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAuxiliarGeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
