/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frames;

import dados.Aluno;
import java.sql.Date;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import persistencia.ControladorDePersistencia;

/**
 *
 * @author Guilherme
 */
public class CadastrarAluno extends javax.swing.JFrame {

    
    int selecionado;
    MenuPrincipal mp;
    ConsultarAluno ca;
    Matricular mt;
    
    Aluno aluno;
    
    
    /**
     * Creates new form CadastrarAluno
     */
    public CadastrarAluno() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }
    
     public CadastrarAluno(MenuPrincipal menu) {
        initComponents();
        mp = menu;
        selecionado = 1;
        jLabel1.setText("Cadastrar Aluno");
        jButton2.setText("Cadastrar");
        this.setLocationRelativeTo(null);
        
    }
     
      public CadastrarAluno(ConsultarAluno consul,Aluno al) {
        initComponents();
        ca = consul;
        aluno = new Aluno();
        aluno.clonarAluno(al);
        selecionado = 2;
        
        jLabel1.setText("Alterar Aluno");
        jButton2.setText("Alterar");
        
        jTextField3.setText(aluno.getNome());
        jTextField2.setText(aluno.getRg());
        jTextField4.setText(aluno.getEndereco());
        jTextField5.setText(aluno.getTelefone());
          //System.out.println("a");
        jDateChooser1.setDate(aluno.getNascimento());
          //System.out.println("b");
        jTextField7.setText(""+aluno.getIdade());
        jTextField8.setText(aluno.getPai());
        jTextField9.setText(aluno.getMae());
        
        //this.jTextField2.setEditable(false);
        
        
        this.setLocationRelativeTo(null);
        
    }
      
      public CadastrarAluno(Matricular mat) {
        initComponents();
        mt = mat;
        selecionado = 3;
        jLabel1.setText("Cadastrar Aluno");
        jButton2.setText("Cadastrar");
        this.setLocationRelativeTo(null);
        
    }
    
    private MaskFormatter setMascara(String mascara){  
    MaskFormatter mask = null;  
    try{  
        mask = new MaskFormatter(mascara);                        
        }catch(java.text.ParseException ex){}  
    return mask;  
}  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastrar Aluno");

        jLabel2.setText("Nome:");

        jLabel3.setText("RG:");

        jLabel4.setText("Endereço:");

        jLabel5.setText("Nascimento:");

        jLabel6.setText("Nome Pai:");

        jLabel7.setText("Idade:");

        jLabel8.setText("Telefone:");

        jLabel9.setText("Nome Mãe:");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField7.setEditable(false);
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField7MouseEntered(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4)
                            .addComponent(jTextField8)
                            .addComponent(jTextField9)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jTextField5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //MenuPrincipal mp = new MenuPrincipal();
        //mp.setVisible(true);
        if(selecionado == 1){
            mp.setEnabled(true);
        }
        if (selecionado == 2){
            ca.setEnabled(true);
        }
        if (selecionado == 3){
            mt.setEnabled(true);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean alunoNaoExistente(Aluno al){
        try{
            ControladorDePersistencia con = new ControladorDePersistencia();
            ArrayList<Aluno> lal = con.carregaAluno();
            for(Aluno a:lal){
                if(a.getRg().equals(al.getRg())){
                    return false;
                }
            }  
        }
        catch(Exception ex){
        }
        return true;
    }
    
    public boolean rgUsado(Aluno al){
        try{
            ControladorDePersistencia con = new ControladorDePersistencia();
            ArrayList<Aluno> lal = con.carregaAluno();
            for(Aluno a:lal){
                if(a.getRg().equals(al.getRg())){
                    if(a.getId() != al.getId()){
                        return true;
                    }
                }
            }  
        }
        catch(Exception ex){
        }
        return false;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try{
            String nome, rg, endereco, telefone, pai, mae;
            int idade;
            
            nome = jTextField3.getText().toString();
            if (nome.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um nome","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            rg = jTextField2.getText().toString();
            if (rg.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um RG","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            endereco = jTextField4.getText().toString();
            if (endereco.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um endereco","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            telefone = jTextField5.getText().toString();
            if (telefone.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um telefone","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }  
            Date data;
            try{
                int ano = jDateChooser1.getCalendar().get(Calendar.YEAR);
                int mes = jDateChooser1.getCalendar().get(Calendar.MONTH);
                int dia = jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
                data = new Date(ano-1900,mes,dia);
                DateFormat format = DateFormat.getDateInstance(DateFormat.SHORT);
                String dt = format.format(data);
            }
            catch(Exception exNascimento){
                JOptionPane.showMessageDialog(this,"Selecione uma data","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            idade = Integer.parseInt(jTextField7.getText().toString());
            pai = jTextField8.getText().toString();
            if (pai.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um nome para PAI","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            mae = jTextField9.getText().toString();
            if (mae.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um nome para Mãe","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int Status = 1;
            
            Aluno a1 = new Aluno(nome, rg, endereco, telefone, data, idade, pai, mae, Status);
            
            ControladorDePersistencia c = new ControladorDePersistencia();
            if(selecionado == 1){
//                System.out.println("cadastrar");
                
                if(alunoNaoExistente(a1)){
                
                    boolean resultado = c.cadastraAluno(a1);
    //                System.out.println("fim");
                    if(resultado){
                        JOptionPane.showMessageDialog(this,"Aluno cadastrado com sucesso");
                        mp.setEnabled(true);
                        dispose();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Aluno já existe");
                    return;
                }
            }
            if(selecionado == 2){
                a1.setId(this.aluno.getId());
                if(rgUsado(a1)){
                    JOptionPane.showMessageDialog(this,"RG utilizado por outro aluno");
                    return;
                }
                boolean resultado = c.alteraAluno(a1);
                if(resultado){
                    JOptionPane.showMessageDialog(this,"Aluno alterado com sucesso");
                    ca.reload();
                    ca.setEnabled(true);
                    dispose();
                }
            }
            if(selecionado == 3){
//                System.out.println("cadastrar");
                boolean resultado = c.cadastraAluno(a1);
//                System.out.println("fim");
                if(resultado){
                    JOptionPane.showMessageDialog(this,"Aluno cadastrado com sucesso");
                    mt.setAluno(a1);
                    mt.setEnabled(true);
                    dispose();
                }
            }
            
        }
        catch(Exception ex){
            
        }
        
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jDateChooser1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDateChooser1KeyTyped

    private void jTextField7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseEntered
        // TODO add your handling code here:
        
        try{
            int ano = jDateChooser1.getCalendar().get(Calendar.YEAR);
            int mes = jDateChooser1.getCalendar().get(Calendar.MONTH);
            int dia = jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
            
            Calendar c = Calendar.getInstance();
//            DateFormat format = DateFormat.getDateInstance(DateFormat.SHORT);
//            String dt = format.format(dataAtual);
//            System.out.println(dt);    
//            System.out.println(dataAtual.getYear());    
            int anos =  c.get(Calendar.YEAR)- ano;
            int meses = c.get(Calendar.MONTH) - mes;
            int dias = c.get(Calendar.DAY_OF_MONTH) - dia;
            anos -= 1;
            if(meses > 0){
                anos += 1;
            }
            if(meses == 0){
                if(dias >= 0){
                    anos += 1;
                }
            }
            jTextField7.setText(""+anos);
            
            
            
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_jTextField7MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        try{
            int ano = jDateChooser1.getCalendar().get(Calendar.YEAR);
            int mes = jDateChooser1.getCalendar().get(Calendar.MONTH);
            int dia = jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
            
            Calendar c = Calendar.getInstance();
//            DateFormat format = DateFormat.getDateInstance(DateFormat.SHORT);
//            String dt = format.format(dataAtual);
//            System.out.println(dt);    
//            System.out.println(dataAtual.getYear());    
            int anos =  c.get(Calendar.YEAR)- ano;
            int meses = c.get(Calendar.MONTH) - mes;
            int dias = c.get(Calendar.DAY_OF_MONTH) - dia;
            anos -= 1;
            if(meses > 0){
                anos += 1;
            }
            if(meses == 0){
                if(dias >= 0){
                    anos += 1;
                }
            }
            jTextField7.setText(""+anos);
            
            
            
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_jButton2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
