/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frames;

import dados.*;
import java.awt.List;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import persistencia.ControladorDePersistencia;

/**
 *
 * @author Guilherme
 */
public class InserirTurma extends javax.swing.JFrame {

    MenuPrincipal mp;
    ConsultarTurma ct;
    
    Curso curso;
    Nivel nivel;
    ArrayList<Nivel> listNivel;
    Funcionario funcionario; 
    Turma turma;
    String nCurso = "";
    
    int selecionado;
    /**
     * Creates new form CadastrarAluno
     */
    public InserirTurma() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public InserirTurma(MenuPrincipal menu) {
        initComponents();
        mp = menu;
        selecionado = 1;
        this.setLocationRelativeTo(null);
    }
    
    public InserirTurma(ConsultarTurma consul, Turma t, Curso c, Nivel n, Funcionario f) {
        initComponents();
        ct = consul;
        turma = new Turma();
        turma.clonarTurma(t);
        curso = new Curso();
        curso.clonarCurso(c);
        nivel = new Nivel();
        nivel.clonarNivel(n);
        funcionario = new Funcionario();
        funcionario.clonarFuncionario(f);
        selecionado = 2;
        jLabel1.setText("Alterar Turma");
        jButton2.setText("Alterar");
        jTextField3.setText(turma.getNome());
        jTextField2.setText(curso.getNome());
        setListNivel();
        selecionaNomeCbox();
        jTextField5.setText(funcionario.getNome());
        jTextField6.setText(""+turma.getVagas());
        jTextArea1.setText(turma.getHorarios());
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Inserir Turma");

        jLabel2.setText("Curso:");

        jLabel3.setText("Horários:");

        jLabel4.setText("Nível:");

        jLabel5.setText("Professor:");

        jLabel7.setText("Vagas:");

        jLabel8.setText("Nome:");

        jTextField2.setEditable(false);

        jTextField5.setEditable(false);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addGap(0, 170, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField5)
                            .addComponent(jTextField2)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(jButton3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (selecionado == 1){
            mp.setEnabled(true);
        }
        if (selecionado == 2){
            ct.setEnabled(true);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String nome, emailprofessor, horarios;
        int id, idcurso, idnivel, vagas, status;
        try{
            nome = jTextField3.getText().toString();
            if(nome.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira um nome.","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(jTextField2.getText().length() == 0){
                JOptionPane.showMessageDialog(this,"Selecione um curso","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            idcurso = curso.getId();
            
            //selecionaNomeCbox();
            try{
                idnivel = listNivel.get(jComboBox1.getSelectedIndex()).getId();
            }
            catch(Exception excbox){
                JOptionPane.showMessageDialog(this,"Selecione um nivel","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if(jTextField5.getText().length() == 0){
                JOptionPane.showMessageDialog(this,"Selecione um professor","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            emailprofessor = funcionario.getEmail();
            try{
                vagas = Integer.parseInt(jTextField6.getText().toString());
            }
            catch(Exception exvaga){
                JOptionPane.showMessageDialog(this,"Insira uma quantidade de vagas válido","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            horarios = jTextArea1.getText().toString();
            if(horarios.length() == 0){
                JOptionPane.showMessageDialog(this,"Insira horários","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }

            
            if(selecionado == 1){
                id = 0;
                status = 1;
                Turma t = new Turma(id, nome, idcurso, idnivel, emailprofessor, vagas, 0,horarios, status);
                ControladorDePersistencia con = new ControladorDePersistencia();

                boolean resultado = con.cadastraTurma(t);
                if(resultado){
                    JOptionPane.showMessageDialog(this,"Turma cadastrado com sucesso","Warning",JOptionPane.WARNING_MESSAGE);
                    mp.setEnabled(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Erro ao cadastrar turma","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            if(selecionado == 2){
                id = turma.getId();
                status = turma.getStatus();
                Turma t = new Turma(id, nome, idcurso, idnivel, emailprofessor, vagas, 0, horarios, status);
                ControladorDePersistencia con = new ControladorDePersistencia();

                boolean resultado = con.alteraTurma(t);
                if(resultado){
                    JOptionPane.showMessageDialog(this,"Turma alterado com sucesso","Warning",JOptionPane.WARNING_MESSAGE);
                    ct.reload();
                    ct.setEnabled(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Erro ao alterar turma","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

        }
        catch(Exception ex){

        }
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ConsultarCurso cc = new ConsultarCurso(this);
        cc.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ConsultarFuncionario cf = new ConsultarFuncionario(this);
        cf.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:
        if(!nCurso.equals(curso.getNome())){
            setListNivel();
            nCurso = curso.getNome();
        }
        
    }//GEN-LAST:event_jComboBox1MouseEntered

    public void setCurso(Curso c){
        curso = new Curso();
        curso.clonarCurso(c);
        //setListNivel();
        //selecionaNomeCbox();
        jTextField2.setText(curso.getNome());
        setListNivel();
    }
    
    
    
    public void setJCBoxNivel(){
//        String[] nivebox = new String[listNivel.size()];
        Vector vetor = new Vector();   
        
        for(int i=0;i<listNivel.size();i++){
            Nivel n = listNivel.get(i);
//            nivebox[i] = n.getNome();
//            System.out.println(""+i+" "+n.getNome());
            vetor.add(n.getNome());
            
        }
        
//        Object[] items = <seu array de objetos>;  
        DefaultComboBoxModel model = new DefaultComboBoxModel(vetor);  
        jComboBox1.setModel(model);  
//        jComboBox1 = new JComboBox(vetor);
//        for (String nb:nivebox){
//            System.out.println(nb);
//            jComboBox1.addItem(new Object[]{
//                                nb,
//
//                                });
//        }
        
        
    }
    
   public void selecionaNomeCbox(){
       for(int i=0;i<listNivel.size();i++){
           Nivel n = listNivel.get(i);
           if(n.getId() == nivel.getId()){
               jComboBox1.setSelectedIndex(i);
           }
       }
   }
       
    
   
    public void setListNivel(){
        try{
            listNivel = new ArrayList<Nivel>();
            ArrayList<Nivel> lstNivel = new ArrayList<Nivel>();
            ControladorDePersistencia con = new ControladorDePersistencia();
            lstNivel = con.carregaNivel();
            //System.out.println(lstNivel.size());
//            nivel = new Nivel();
            for(Nivel n:lstNivel){
//                System.out.println(n.getIdcurso()+"-"+curso.getId());
                if(n.getIdcurso() == curso.getId()){
//                    System.out.println(n.getNome());
                    Nivel n2 = new Nivel();
                    n2.clonarNivel(n);
//                    nivel.clonarNivel(n);
                    listNivel.add(n2);
                }
            }
            setJCBoxNivel();
        }
        catch(Exception ex){
            
        }
    }
   
    
    public void setNivel(){
        try{
            ArrayList<Nivel> listNivel = new ArrayList<Nivel>();
            ControladorDePersistencia con = new ControladorDePersistencia();
            listNivel = con.carregaNivel();
            nivel = new Nivel();
            for(Nivel n:listNivel){
//                System.out.println(n.getIdcurso()+"-"+curso.getId());
                if(n.getIdcurso() == curso.getId()){
                    nivel.clonarNivel(n);
                    return;
                }
            }
        }
        catch(Exception ex){
            
        }
    }
     
    public void setProfessor(Funcionario f){
        funcionario = new Funcionario();
        funcionario.clonarFuncionario(f);
        this.jTextField5.setText(funcionario.getNome());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
